apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels:
    app: k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s
  template:
    metadata:
      labels:
        app: k8s
    spec:
      initContainers:
        - {{ include "audittail.initContainer" .}}
      containers:
        - name: nginx
          image: nginx:v1
            args:
              - --audit-log-path={{ template "audittail.auditLogPath" }}
          volumeMounts:
            - {{ include "audittail.volumeMount" . }}
      volumes:
        - {{ include "audittail.volume" . }}

